import type { SiteTokens, TokenCssVarMap } from './types';

export const SITE_TOKEN_CSS_VARIABLES = {
	colors: {
		background: '--site-color-bg',
		backgroundSoft: '--site-color-bg-soft',
		surface: '--site-color-panel',
		surfaceSoft: '--site-color-surface-soft',
		text: '--site-color-text',
		textMuted: '--site-color-text-muted',
		border: '--site-color-border',
		borderSoft: '--site-color-border-soft',
		accent: '--site-color-accent',
		accentHover: '--site-color-accent-hover',
		accentContrast: '--site-color-accent-contrast',
		headerBackground: '--site-color-header-bg',
		headerText: '--site-color-header-text',
		headerBorder: '--site-color-header-border',
		footerBackground: '--site-color-footer-bg',
		footerText: '--site-color-footer-text',
		footerBorder: '--site-color-footer-border',
		success: '--site-color-success',
		warning: '--site-color-warning',
		danger: '--site-color-danger',
	},
	typography: {
		bodyFont: '--site-font-body',
		headingFont: '--site-font-heading',
		brandFont: '--site-font-brand',
		navFont: '--site-font-nav',
		bodySize: '--site-font-size-body',
		smallSize: '--site-font-size-small',
		headingLineHeight: '--site-line-height-heading',
		bodyLineHeight: '--site-line-height-body',
		regularWeight: '--site-font-weight-regular',
		mediumWeight: '--site-font-weight-medium',
		semiboldWeight: '--site-font-weight-semibold',
	},
	radii: {
		panel: '--site-radius-panel',
		card: '--site-radius-card',
		button: '--site-radius-button',
		input: '--site-radius-input',
	},
	spacing: {
		section: '--site-space-section',
		pageGutter: '--site-space-page-gutter',
		cardPadding: '--site-space-card-padding',
		fieldGap: '--site-space-field-gap',
		stackGap: '--site-space-stack-gap',
		inlineGap: '--site-space-inline-gap',
	},
	layout: {
		containerWidth: '--site-container-width',
		contentWidth: '--site-content-width',
		formWidth: '--site-form-width',
	},
	buttons: {
		background: '--site-color-button-bg',
		backgroundHover: '--site-color-button-bg-hover',
		text: '--site-color-button-text',
		textHover: '--site-color-button-text-hover',
		border: '--site-button-border-color',
		radius: '--site-button-radius',
		paddingX: '--site-button-padding-x',
		paddingY: '--site-button-padding-y',
		hoverStyle: '--site-button-hover-style',
		hoverDecoration: '--site-button-hover-decoration',
		focusRing: '--site-button-focus-ring',
	},
	inputs: {
		background: '--site-input-bg',
		text: '--site-input-text',
		placeholder: '--site-input-placeholder',
		border: '--site-input-border',
		radius: '--site-input-radius',
		paddingX: '--site-input-padding-x',
		paddingY: '--site-input-padding-y',
		focusRing: '--site-input-focus-ring',
	},
} as const;

export function siteTokensToCssVarMap(tokens: SiteTokens): TokenCssVarMap {
	return {
		'--site-color-bg': tokens.colors.background,
		'--site-color-bg-soft': tokens.colors.backgroundSoft,
		'--site-color-panel': tokens.colors.surface,
		'--site-color-surface-soft': tokens.colors.surfaceSoft,
		'--site-color-text': tokens.colors.text,
		'--site-color-text-muted': tokens.colors.textMuted,
		'--site-color-border': tokens.colors.border,
		'--site-color-border-soft': tokens.colors.borderSoft,
		'--site-color-accent': tokens.colors.accent,
		'--site-color-accent-hover': tokens.colors.accentHover,
		'--site-color-accent-contrast': tokens.colors.accentContrast,
		'--site-color-header-bg': tokens.colors.headerBackground,
		'--site-color-header-text': tokens.colors.headerText,
		'--site-color-header-border': tokens.colors.headerBorder,
		'--site-color-footer-bg': tokens.colors.footerBackground,
		'--site-color-footer-text': tokens.colors.footerText,
		'--site-color-footer-border': tokens.colors.footerBorder,
		'--site-color-button-bg': tokens.buttons.background,
		'--site-color-button-bg-hover': tokens.buttons.backgroundHover,
		'--site-color-button-text': tokens.buttons.text,
		'--site-color-button-text-hover': tokens.buttons.textHover,
		'--site-color-success': tokens.colors.success,
		'--site-color-warning': tokens.colors.warning,
		'--site-color-danger': tokens.colors.danger,
		'--site-font-body': tokens.typography.bodyFont,
		'--site-font-heading': tokens.typography.headingFont,
		'--site-font-brand': tokens.typography.brandFont,
		'--site-font-siteName': tokens.typography.brandFont,
		'--font-brand': tokens.typography.brandFont,
		'--site-font-nav': tokens.typography.navFont,
		'--site-font-size-body': tokens.typography.bodySize,
		'--site-font-size-small': tokens.typography.smallSize,
		'--site-line-height-heading': tokens.typography.headingLineHeight,
		'--site-line-height-body': tokens.typography.bodyLineHeight,
		'--site-font-weight-regular': tokens.typography.regularWeight,
		'--site-font-weight-medium': tokens.typography.mediumWeight,
		'--site-font-weight-semibold': tokens.typography.semiboldWeight,
		'--site-container-width': tokens.layout.containerWidth,
		'--site-content-width': tokens.layout.contentWidth,
		'--site-form-width': tokens.layout.formWidth,
		'--site-radius-panel': tokens.radii.panel,
		'--site-radius-card': tokens.radii.card,
		'--site-radius-button': tokens.radii.button,
		'--site-radius-input': tokens.radii.input,
		'--site-space-section': tokens.spacing.section,
		'--site-space-page-gutter': tokens.spacing.pageGutter,
		'--site-space-card-padding': tokens.spacing.cardPadding,
		'--site-space-field-gap': tokens.spacing.fieldGap,
		'--site-space-stack-gap': tokens.spacing.stackGap,
		'--site-space-inline-gap': tokens.spacing.inlineGap,
		'--site-button-border-color': tokens.buttons.border,
		'--site-button-radius': tokens.buttons.radius,
		'--site-button-padding-x': tokens.buttons.paddingX,
		'--site-button-padding-y': tokens.buttons.paddingY,
		'--site-button-hover-style': tokens.buttons.hoverStyle,
		'--site-button-hover-decoration': tokens.buttons.hoverDecoration,
		'--site-button-focus-ring': tokens.buttons.focusRing,
		'--site-input-bg': tokens.inputs.background,
		'--site-input-text': tokens.inputs.text,
		'--site-input-placeholder': tokens.inputs.placeholder,
		'--site-input-border': tokens.inputs.border,
		'--site-input-radius': tokens.inputs.radius,
		'--site-input-padding-x': tokens.inputs.paddingX,
		'--site-input-padding-y': tokens.inputs.paddingY,
		'--site-input-focus-ring': tokens.inputs.focusRing,
	};
}

export function siteTokensToCssVars(tokens: SiteTokens): string {
	return Object.entries(siteTokensToCssVarMap(tokens))
		.map(([name, value]) => `${name}: ${value}`)
		.join('; ');
}
