import type { SiteTokens } from './types';

export const DEFAULT_SITE_TOKENS: SiteTokens = {
	colors: {
		background: '#fffef4',
		backgroundSoft: '#f8f3c4',
		surface: '#f3f7d9',
		surfaceSoft: '#f8f3c4',
		text: '#243018',
		textMuted: '#556348',
		border: '#7a8b4d',
		borderSoft: '#7a8b4d',
		accent: '#556b2f',
		accentHover: '#445625',
		accentContrast: '#fffef4',
		headerBackground: '#f8f3c4',
		headerText: '#243018',
		headerBorder: '#7a8b4d',
		footerBackground: '#dbe6b0',
		footerText: '#2b381c',
		footerBorder: '#6e8046',
		success: '#166534',
		warning: '#92400e',
		danger: '#991b1b',
	},
	typography: {
		bodyFont: 'system-ui, sans-serif',
		headingFont: 'system-ui, sans-serif',
		brandFont: 'system-ui, sans-serif',
		navFont: 'system-ui, sans-serif',
		bodySize: '1rem',
		smallSize: '0.875rem',
		headingLineHeight: '1.2',
		bodyLineHeight: '1.5',
		regularWeight: '400',
		mediumWeight: '500',
		semiboldWeight: '600',
	},
	radii: {
		panel: '1rem',
		card: '1rem',
		button: '0.5rem',
		input: '6px',
	},
	spacing: {
		section: '5rem',
		pageGutter: '1.5rem',
		cardPadding: '1rem',
		fieldGap: '0.25rem',
		stackGap: '1rem',
		inlineGap: '0.75rem',
	},
	layout: {
		containerWidth: '72rem',
		contentWidth: '48rem',
		formWidth: '42rem',
	},
	buttons: {
		background: '#556b2f',
		backgroundHover: '#445625',
		text: '#fffef4',
		textHover: '#fffef4',
		border: '#556b2f',
		radius: '0.5rem',
		paddingX: '1rem',
		paddingY: '0.625rem',
		hoverStyle: 'underline',
		hoverDecoration: 'underline',
		focusRing: '#2563eb',
	},
	inputs: {
		background: '#ffffff',
		text: '#111827',
		placeholder: '#6b7280',
		border: '#d1d5db',
		radius: '6px',
		paddingX: '0.75rem',
		paddingY: '0.5rem',
		focusRing: '#2563eb',
	},
};
